### ISSUE TITLE
Errors in tests in Racket 7.3

### ISSUE THREAD

**Issue by gus-massa** [lexi-lambda/racket-r7rs#11]
I run the test suit in Racket 7.3 and I got four errors: [travis test results#L630](https://travis-ci.org/gus-massa/racket-r7rs/jobs/533353486#L630). They are caused by changes in the previous versions of Racket. I found the exact commits that changed the behavior,  so I'll report the changes there to see if they will reverted or if this is the new official behavior.

The test are:

* [r7rs-tests.rkt#L2030](https://github.com/lexi-lambda/racket-r7rs/blob/master/r7rs-test/tests/r7rs/chibi/tests/r7rs-tests.rkt#L2030) `(test 'abc (read (open-input-string "#!fold-case ABC")))`
* [r7rs-tests.rkt#L2031](https://github.com/lexi-lambda/racket-r7rs/blob/master/r7rs-test/tests/r7rs/chibi/tests/r7rs-tests.rkt#L2031) `(test 'ABC (read (open-input-string "#!fold-case #!no-fold-case ABC")))`

* [r7rs-tests.rkt#L2181](https://github.com/lexi-lambda/racket-r7rs/blob/master/r7rs-test/tests/r7rs/chibi/tests/r7rs-tests.rkt#L2181) `(test-numeric-syntax "1+2I" (make-rectangular 1 2) "1+2i")` (double error in tests)

**Comment by lexi-lambda** [comment]
This doesn’t seem to be an issue anymore, so I’m going to close this.
