### ISSUE TITLE
with-input-from-file doesn't exist.

### ISSUE THREAD

**Issue by johannesCmayer** [lexi-lambda/racket-r7rs#23]
I think this code should work (it works in chibi) but in drracket I get 
`advent_2.rkt:7:3: with-input-from-file: unbound identifier  in: with-input-from-file  #(91 20)`

The weird thing is that drracket still provides a completion for it. Probably I am just making a very dumb mistake.

```
#lang r7rs

(import (scheme base)
        (scheme write))

(define main (lambda (args)
  (with-input-from-file "data.txt"
    (lambda () 
      (display (read-line))))))
```

**Comment by lexi-lambda** [comment]
`with-input-from-file` is provided by the `(scheme file)` library, not `(scheme base)` or `(scheme write)`. This is documented in [the report](https://small.r7rs.org/attachment/r7rs.pdf).
