### ISSUE TITLE
Recursive promises

### ISSUE THREAD

**Issue by jmhufflen** [lexi-lambda/racket-r7rs#9]
Let us consider the following recursive promise:

```scheme
(define x 0)
(define p (delay (if (= x 5)  x
                                (begin
                                  (set! x (+ x 1))
                                  (force p)
                                  (set! x (+ x 1))
                                  x))))
```

I know that there is several semantics interpretations of such a promise, but what is strange and probably faultly: the 1st call to "force" does not yield the same result than others:

```scheme
(force p) => 10
(force p) => 5
(force p) => 5 ; and forever.
```

What do you think, please? Yours sincerely,

J.-M.

**Comment by Lysias-1998** [comment]
when (force p) returned the first time,  x=5, so it is 5 that thunk p remembers. 

The 5 is dropped in the definition of p,  then the recursive function returned 5 more times and made x 10. 

But the later call to (force p) refers to the remembered value,  which is 5, not the value of x, in this case. 

Your example shows that it is hard to use assignments and lazy evaluations at the same time.
